# 1. Setup Verification

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
print("NumPy version:", np.__version__)
print("Array example:\n", np.array([1, 2, 3]))

NumPy version: 2.2.4
Array example:
 [1 2 3]


# 2. Core Concepts Review

## A. Array Creation

In [5]:
# Basic arrays
a = np.array([1, 2, 3])                   # 1D array
b = np.array([[1, 2], [3, 4]])            # 2D array  

# Special arrays
zeros = np.zeros((2, 3))                  # 2x3 zeros matrix  
ones = np.ones((3,))                      # 1D vector of 1's
range_arr = np.arange(0, 10, 2)           # Like range() but returns array

In [6]:
print(f"a = {a}\n")
print(f"b = {b}\n")

print(f"zeros = {zeros}\n")
print(f"ones = {ones}\n")
print(f"range_arr = {range_arr}\n")


a = [1 2 3]

b = [[1 2]
 [3 4]]

zeros = [[0. 0. 0.]
 [0. 0. 0.]]

ones = [1. 1. 1.]

range_arr = [0 2 4 6 8]



## B. Array Operations

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Element-wise sum:", x + y)          # [5 7 9]
print("Dot product:", np.dot(x, y))       # 32
print("Broadcasted multiply:", x * 2)     # [2 4 6]

Element-wise sum: [5 7 9]
Dot product: 32
Broadcasted multiply: [2 4 6]


## C. Indexing & Slicing

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("First row:", matrix[0])            # [1 2 3]
print("Second column:", matrix[:, 1])     # [2 5 8]  
print("Submatrix:\n", matrix[1:, :2])     # [[4 5], [7 8]]

First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[4 5]
 [7 8]]


## D. Reshaping & Stacking

In [9]:
arr = np.arange(6)
print("Reshaped to 2x3:\n", arr.reshape(2, 3))

# Stacking arrays
a = np.array([1, 2])
b = np.array([3, 4])
print("Vertical stack:\n", np.vstack((a, b)))  # [[1 2], [3 4]]
print("Horizontal stack:\n", np.hstack((a, b)))  # [[1 2], [3 4]]

Reshaped to 2x3:
 [[0 1 2]
 [3 4 5]]
Vertical stack:
 [[1 2]
 [3 4]]
Horizontal stack:
 [1 2 3 4]


# 3. Performance Demonstration

## TODO